version: 1

formatters:
  simple:
    format: '%(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  normal:
    format: '%(asctime)s.%(msecs)03d|%(levelname)-8s|%(name)-15s|%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: normal
    filename: logs/dev.log
    level: DEBUG
    maxBytes: 10485760 # 10MB
    backupCount: 10

loggers:
  commonLog:
    level: DEBUG
    handlers: [console, file]
    propagate: 1
  root:
    level: DEBUG
    handlers: [console]
